services:
  poo-ts:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
    env_file:
      - .env
    ports:
      - 3000:3000
  nginx:
    image: nginx:1.19.10-alpine
    restart: always
    ports: - 4000:80
    volumes: ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  db:
    image: mysql:8.0.30-debian
      

